package nominatim

type CountryLanguages struct {
	name      string
	cc        string
	languages []string
}

var WorldWideLanguages = []CountryLanguages{
	{cc: "AD", name: "Andorra", languages: []string{"ca"}},
	{cc: "AE", name: "United Arab Emirates", languages: []string{"ar"}},
	{cc: "AF", name: "Afghanistan", languages: []string{"fa", "ps"}},
	{cc: "AG", name: "Antigua and Barbuda", languages: []string{"en"}},
	{cc: "AI", name: "Anguilla", languages: []string{"en"}},
	{cc: "AL", name: "Albania", languages: []string{"sq"}},
	{cc: "AM", name: "Armenia", languages: []string{"hy"}},
	{cc: "AO", name: "Angola", languages: []string{"pt"}},
	{cc: "AQ", name: "Antarctica", languages: []string{"en", "es", "fr", "ru"}},
	{cc: "AR", name: "Argentina", languages: []string{"es"}},
	{cc: "AS", name: "American Samoa", languages: []string{"en", "sm"}},
	{cc: "AT", name: "Austria", languages: []string{"de"}},
	{cc: "AU", name: "Australia", languages: []string{"en"}},
	{cc: "AW", name: "Aruba", languages: []string{"nl", "pap"}},
	{cc: "AX", name: "Aland Islands", languages: []string{"sv"}},
	{cc: "AZ", name: "Azerbaijan", languages: []string{"az"}},
	{cc: "BA", name: "Bosnia and Herzegovina", languages: []string{"bs", "hr", "sr"}},
	{cc: "BB", name: "Barbados", languages: []string{"en"}},
	{cc: "BD", name: "Bangladesh", languages: []string{"bn"}},
	{cc: "BE", name: "Belgium", languages: []string{"nl", "fr", "de"}},
	{cc: "BF", name: "Burkina Faso", languages: []string{"fr"}},
	{cc: "BG", name: "Bulgaria", languages: []string{"bg"}},
	{cc: "BH", name: "Bahrain", languages: []string{"ar"}},
	{cc: "BI", name: "Burundi", languages: []string{"fr"}},
	{cc: "BJ", name: "Benin", languages: []string{"fr"}},
	{cc: "BL", name: "Saint Barthélemy", languages: []string{"fr"}},
	{cc: "BM", name: "Bermuda", languages: []string{"en"}},
	{cc: "BN", name: "Brunei Darussalam", languages: []string{"ms"}},
	{cc: "BO", name: "Bolivia", languages: []string{"es", " qu", "gn", "ay"}},
	{cc: "BQ", name: "Caribbean Netherlands", languages: []string{"nl"}},
	{cc: "BR", name: "Brazil", languages: []string{"pt"}},
	{cc: "BS", name: "Bahamas", languages: []string{"en"}},
	{cc: "BT", name: "Bhutan", languages: []string{"dz"}},
	{cc: "BV", name: "Bouvet Island", languages: []string{"no"}},
	{cc: "BW", name: "Botswana", languages: []string{"en", "tn"}},
	{cc: "BY", name: "Belarus", languages: []string{"be", "ru"}},
	{cc: "BZ", name: "Belize", languages: []string{"en"}},
	{cc: "CA", name: "Canada", languages: []string{"en", "fr"}},
	{cc: "CC", name: "Cocos (Keeling) Islands", languages: []string{"en"}},
	{cc: "CD", name: "Democratic Republic of the Congo (Congo-Kinshasa, former Zaire)", languages: []string{"fr"}},
	{cc: "CF", name: "Centrafrican Republic", languages: []string{"fr", "sg"}},
	{cc: "CG", name: "Republic of the Congo (Congo-Brazzaville)", languages: []string{"fr"}},
	{cc: "CH", name: "Switzerland", languages: []string{"de", "fr", "it", "rm"}},
	{cc: "CI", name: "Côte d'Ivoire", languages: []string{"fr"}},
	{cc: "CK", name: "Cook Islands", languages: []string{"en", "rar"}},
	{cc: "CL", name: "Chile", languages: []string{"es"}},
	{cc: "CM", name: "Cameroon", languages: []string{"fr", "en"}},
	{cc: "CN", name: "China", languages: []string{"zh-hans"}},
	{cc: "CO", name: "Colombia", languages: []string{"es"}},
	{cc: "CR", name: "Costa Rica", languages: []string{"es"}},
	{cc: "CU", name: "Cuba", languages: []string{"es"}},
	{cc: "CV", name: "Cabo Verde", languages: []string{"pt"}},
	{cc: "CW", name: "Curaçao", languages: []string{"nl", "en"}},
	{cc: "CX", name: "Christmas Island", languages: []string{"en"}},
	{cc: "CY", name: "Cyprus", languages: []string{"el", "tr"}},
	{cc: "CZ", name: "Czech Republic", languages: []string{"cs"}},
	{cc: "DE", name: "Germany", languages: []string{"de"}},
	{cc: "DJ", name: "Djibouti", languages: []string{"fr", "ar", "so", "aa"}},
	{cc: "DK", name: "Denmark", languages: []string{"da"}},
	{cc: "DM", name: "Dominica", languages: []string{"en"}},
	{cc: "DO", name: "Dominican Republic", languages: []string{"es"}},
	{cc: "DZ", name: "Algeria", languages: []string{"ar"}},
	{cc: "EC", name: "Ecuador", languages: []string{"es"}},
	{cc: "EE", name: "Estonia", languages: []string{"et"}},
	{cc: "EG", name: "Egypt", languages: []string{"ar"}},
	{cc: "EH", name: "Western Sahara", languages: []string{"ar", "es", "fr"}},
	{cc: "ER", name: "Eritrea", languages: []string{"ti", "ar", "en"}},
	{cc: "ES", name: "Spain", languages: []string{"ast", "ca", "es", "eu", "gl"}},
	{cc: "ET", name: "Ethiopia", languages: []string{"am", "om"}},
	{cc: "FI", name: "Finland", languages: []string{"fi", "sv", "se"}},
	{cc: "FJ", name: "Fiji", languages: []string{"en"}},
	{cc: "FK", name: "Falkland Islands", languages: []string{"en"}},
	{cc: "FM", name: "Micronesia (Federated States of)", languages: []string{"en"}},
	{cc: "FO", name: "Faroe Islands", languages: []string{"fo", "da"}},
	{cc: "FR", name: "France", languages: []string{"fr"}},
	{cc: "GA", name: "Gabon", languages: []string{"fr"}},
	{cc: "GB", name: "United Kingdom", languages: []string{"en", "ga", "cy", "gd", "kw"}},
	{cc: "GD", name: "Grenada", languages: []string{"en"}},
	{cc: "GE", name: "Georgia", languages: []string{"ka"}},
	{cc: "GF", name: "French Guiana", languages: []string{"fr"}},
	{cc: "GG", name: "Guernsey", languages: []string{"en"}},
	{cc: "GH", name: "Ghana", languages: []string{"en"}},
	{cc: "GI", name: "Gibraltar", languages: []string{"en"}},
	{cc: "GL", name: "Greenland", languages: []string{"kl", "da"}},
	{cc: "GM", name: "The Gambia", languages: []string{"en"}},
	{cc: "GN", name: "Guinea", languages: []string{"fr"}},
	{cc: "GP", name: "Guadeloupe", languages: []string{"fr"}},
	{cc: "GQ", name: "Equatorial Guinea", languages: []string{"es", "fr", "pt"}},
	{cc: "GR", name: "Greece", languages: []string{"el"}},
	{cc: "GS", name: "South Georgia and the South Sandwich Islands", languages: []string{"en"}},
	{cc: "GT", name: "Guatemala", languages: []string{"es"}},
	{cc: "GU", name: "Guam", languages: []string{"en", "ch"}},
	{cc: "GW", name: "Guinea Bissau", languages: []string{"pt"}},
	{cc: "GY", name: "Guyana", languages: []string{"en"}},
	{cc: "HK", name: "Hong Kong (SAR of China)", languages: []string{"zh-hant", "en"}},
	{cc: "HM", name: "Heard Island and McDonald Islands", languages: []string{"en"}},
	{cc: "HN", name: "Honduras", languages: []string{"es"}},
	{cc: "HR", name: "Croatia", languages: []string{"hr"}},
	{cc: "HT", name: "Haiti", languages: []string{"fr", "ht"}},
	{cc: "HU", name: "Hungary", languages: []string{"hu"}},
	{cc: "ID", name: "Indonesia", languages: []string{"id"}},
	{cc: "IE", name: "Ireland", languages: []string{"en", "ga"}},
	{cc: "IL", name: "Israel", languages: []string{"he"}},
	{cc: "IM", name: "Isle of Man", languages: []string{"en"}},
	{cc: "IN", name: "India", languages: []string{"hi", "en"}},
	{cc: "IO", name: "British Indian Ocean Territory", languages: []string{"en"}},
	{cc: "IQ", name: "Iraq", languages: []string{"ar", "ku"}},
	{cc: "IR", name: "Iran", languages: []string{"fa"}},
	{cc: "IS", name: "Iceland", languages: []string{"is"}},
	{cc: "IT", name: "Italy", languages: []string{"it", "de", "fr"}},
	{cc: "JE", name: "Jersey", languages: []string{"en"}},
	{cc: "JM", name: "Jamaica", languages: []string{"en"}},
	{cc: "JO", name: "Jordan", languages: []string{"ar"}},
	{cc: "JP", name: "Japan", languages: []string{"ja"}},
	{cc: "KE", name: "Kenya", languages: []string{"sw", "en"}},
	{cc: "KG", name: "Kyrgyzstan", languages: []string{"ky", "ru"}},
	{cc: "KH", name: "Cambodia", languages: []string{"km"}},
	{cc: "KI", name: "Kiribati", languages: []string{"en"}},
	{cc: "KM", name: "Comores", languages: []string{"ar", "fr", "sw"}},
	{cc: "KN", name: "Saint Kitts and Nevis", languages: []string{"en"}},
	{cc: "KP", name: "North Korea", languages: []string{"ko"}},
	{cc: "KR", name: "South Korea", languages: []string{"ko"}},
	{cc: "KW", name: "Kuwait", languages: []string{"ar"}},
	{cc: "KY", name: "Cayman Islands", languages: []string{"en"}},
	{cc: "KZ", name: "Kazakhstan", languages: []string{"kk", "ru"}},
	{cc: "LA", name: "Laos", languages: []string{"lo"}},
	{cc: "LB", name: "Lebanon", languages: []string{"ar", "fr"}},
	{cc: "LC", name: "Saint Lucia", languages: []string{"en"}},
	{cc: "LI", name: "Liechtenstein", languages: []string{"de"}},
	{cc: "LK", name: "Sri Lanka", languages: []string{"si", "ta"}},
	{cc: "LR", name: "Liberia", languages: []string{"en"}},
	{cc: "LS", name: "Lesotho", languages: []string{"en", "st"}},
	{cc: "LT", name: "Lithuania", languages: []string{"lt"}},
	{cc: "LU", name: "Luxembourg", languages: []string{"lb", "fr", "de"}},
	{cc: "LV", name: "Latvia", languages: []string{"lv"}},
	{cc: "LY", name: "Libya", languages: []string{"ar"}},
	{cc: "MA", name: "Morocco", languages: []string{"ar", "fr", "zgh"}},
	{cc: "MC", name: "Monaco", languages: []string{"fr"}},
	{cc: "MD", name: "Moldova", languages: []string{"ro", "ru", "uk"}},
	{cc: "ME", name: "Montenegro", languages: []string{"srp", "sr", "hr", "bs", "sq"}},
	{cc: "MF", name: "Saint Martin (French part)", languages: []string{"fr"}},
	{cc: "MG", name: "Madagascar", languages: []string{"mg", "fr"}},
	{cc: "MH", name: "Marshall Islands", languages: []string{"en", "mh"}},
	{cc: "MK", name: "North Macedonia", languages: []string{"mk"}},
	{cc: "ML", name: "Mali", languages: []string{"fr"}},
	{cc: "MM", name: "Myanmar", languages: []string{"my"}},
	{cc: "MN", name: "Mongolia", languages: []string{"mn"}},
	{cc: "MO", name: "Macao (SAR of China)", languages: []string{"zh-hant", "pt"}},
	{cc: "MP", name: "Northern Mariana Islands", languages: []string{"en", "ch"}},
	{cc: "MQ", name: "Martinique", languages: []string{"fr"}},
	{cc: "MR", name: "Mauritania", languages: []string{"ar", "fr"}},
	{cc: "MS", name: "Montserrat", languages: []string{"en"}},
	{cc: "MT", name: "Malta", languages: []string{"mt", "en"}},
	{cc: "MU", name: "Mauritius", languages: []string{"mfe", "fr", "en"}},
	{cc: "MV", name: "Maldives", languages: []string{"dv"}},
	{cc: "MW", name: "Malawi", languages: []string{"en", "ny"}},
	{cc: "MX", name: "Mexico", languages: []string{"es"}},
	{cc: "MY", name: "Malaysia", languages: []string{"ms"}},
	{cc: "MZ", name: "Mozambique", languages: []string{"pt"}},
	{cc: "NA", name: "Namibia", languages: []string{"en", "sf", "de"}},
	{cc: "NC", name: "New Caledonia", languages: []string{"fr"}},
	{cc: "NE", name: "Niger", languages: []string{"fr"}},
	{cc: "NF", name: "Norfolk Island", languages: []string{"en", "pih"}},
	{cc: "NG", name: "Nigeria", languages: []string{"en"}},
	{cc: "NI", name: "Nicaragua", languages: []string{"es"}},
	{cc: "NL", name: "The Netherlands", languages: []string{"nl"}},
	{cc: "NO", name: "Norway", languages: []string{"nb", "nn", "no", "se"}},
	{cc: "NP", name: "Nepal", languages: []string{"ne"}},
	{cc: "NR", name: "Nauru", languages: []string{"na", "en"}},
	{cc: "NU", name: "Niue", languages: []string{"niu", "en"}},
	{cc: "NZ", name: "New Zealand", languages: []string{"mi", "en"}},
	{cc: "OM", name: "Oman", languages: []string{"ar"}},
	{cc: "PA", name: "Panama", languages: []string{"es"}},
	{cc: "PE", name: "Peru", languages: []string{"es"}},
	{cc: "PF", name: "French Polynesia", languages: []string{"fr"}},
	{cc: "PG", name: "Papua  New Guinea", languages: []string{"en", "tpi", "ho"}},
	{cc: "PH", name: "Philippines", languages: []string{"en", "tl"}},
	{cc: "PK", name: "Pakistan", languages: []string{"en", "ur"}},
	{cc: "PL", name: "Poland", languages: []string{"pl"}},
	{cc: "PM", name: "Saint Pierre and Miquelon", languages: []string{"fr"}},
	{cc: "PN", name: "Pitcairn", languages: []string{"en", "pih"}},
	{cc: "PR", name: "Puerto Rico", languages: []string{"es", "en"}},
	{cc: "PS", name: "Palestinian Territory", languages: []string{"ar", "he"}},
	{cc: "PT", name: "Portugal", languages: []string{"pt"}},
	{cc: "PW", name: "Palau", languages: []string{"en", "pau", "ja", "sov", "tox"}},
	{cc: "PY", name: "Paraguay", languages: []string{"es", "gn"}},
	{cc: "QA", name: "Qatar", languages: []string{"ar"}},
	{cc: "RE", name: "Reunion", languages: []string{"fr"}},
	{cc: "RO", name: "Romania", languages: []string{"ro"}},
	{cc: "RS", name: "Serbia", languages: []string{"sr", "sr-Latn"}},
	{cc: "RU", name: "Russia", languages: []string{"ru"}},
	{cc: "RW", name: "Rwanda", languages: []string{"rw", "fr", "en"}},
	{cc: "SA", name: "Saudi Arabia", languages: []string{"ar"}},
	{cc: "SB", name: "Solomon Islands", languages: []string{"en"}},
	{cc: "SC", name: "Seychelles", languages: []string{"fr", "en", "crs"}},
	{cc: "SD", name: "Sudan", languages: []string{"ar", "en"}},
	{cc: "SE", name: "Sweden", languages: []string{"sv"}},
	{cc: "SG", name: "Singapore", languages: []string{"zh-hans", "en", "ms", "ta"}},
	{cc: "SH", name: "Saint Helena", languages: []string{"en"}},
	{cc: "SI", name: "Slovenia", languages: []string{"sl"}},
	{cc: "SJ", name: "Svalbard and Jan Mayen", languages: []string{"no"}},
	{cc: "SK", name: "Slovakia", languages: []string{"sk"}},
	{cc: "SL", name: "Sierra Leone", languages: []string{"en"}},
	{cc: "SM", name: "San Marino", languages: []string{"it"}},
	{cc: "SN", name: "Sénégal", languages: []string{"fr"}},
	{cc: "SO", name: "Somalia", languages: []string{"so", "ar"}},
	{cc: "SR", name: "Suriname", languages: []string{"nl"}},
	{cc: "ST", name: "São Tomé and Príncipe ", languages: []string{"pt"}},
	{cc: "SS", name: "South Sudan", languages: []string{"en"}},
	{cc: "SV", name: "El Salvador", languages: []string{"es"}},
	{cc: "SX", name: "Saint Martin (Dutch part)", languages: []string{"nl", "en"}},
	{cc: "SY", name: "Syria", languages: []string{"ar"}},
	{cc: "SZ", name: "eSwatini", languages: []string{"en", "ss"}},
	{cc: "TC", name: "Turks and Caicos Islands", languages: []string{"en"}},
	{cc: "TD", name: "Chad", languages: []string{"fr", "ar"}},
	{cc: "TF", name: "French Southern and Antarctic Lands", languages: []string{"fr"}},
	{cc: "TG", name: "Togo", languages: []string{"fr"}},
	{cc: "TH", name: "Thailand", languages: []string{"th"}},
	{cc: "TJ", name: "Tajikistan", languages: []string{"tg", "ru"}},
	{cc: "TK", name: "Tokelau", languages: []string{"tkl", "en", "sm"}},
	{cc: "TL", name: "Timor Leste", languages: []string{"pt", "tet"}},
	{cc: "TM", name: "Turkmenistan", languages: []string{"tk"}},
	{cc: "TN", name: "Tunisia", languages: []string{"ar", "fr"}},
	{cc: "TO", name: "Tonga", languages: []string{"en"}},
	{cc: "TR", name: "Turkey", languages: []string{"tr"}},
	{cc: "TT", name: "Trinidad and Tobago ", languages: []string{"en"}},
	{cc: "TV", name: "Tuvalu", languages: []string{"en"}},
	{cc: "TW", name: "Taiwan", languages: []string{"zh-hant"}},
	{cc: "TZ", name: "Tanzania", languages: []string{"sw", "en"}},
	{cc: "UA", name: "Ukraine", languages: []string{"uk"}},
	{cc: "UG", name: "Uganda", languages: []string{"en", "sw"}},
	{cc: "UM", name: "United States Minor Outlying Islands", languages: []string{"en"}},
	{cc: "US", name: "United States of America", languages: []string{"en"}},
	{cc: "UY", name: "Uruguay", languages: []string{"es"}},
	{cc: "UZ", name: "Uzbekistan", languages: []string{"uz", "kaa"}},
	{cc: "VA", name: "City of the Vatican", languages: []string{"it"}},
	{cc: "VC", name: "Saint Vincent and the Grenadines", languages: []string{"en"}},
	{cc: "VE", name: "Venezuela", languages: []string{"es"}},
	{cc: "VG", name: "British Virgin Islands", languages: []string{"en"}},
	{cc: "VI", name: "United States Virgin Islands", languages: []string{"en"}},
	{cc: "VN", name: "Vietnam", languages: []string{"vi"}},
	{cc: "VU", name: "Vanuatu", languages: []string{"bi", "en", "fr"}},
	{cc: "WF", name: "Wallis and Futuna", languages: []string{"fr"}},
	{cc: "WS", name: "Samoa", languages: []string{"sm", "en"}},
	{cc: "XK", name: "Kosovo", languages: []string{"en", "af"}},
	{cc: "YE", name: "Yemen", languages: []string{"ar"}},
	{cc: "YT", name: "Mayotte", languages: []string{"fr"}},
	{cc: "ZA", name: "South Africa", languages: []string{"en", "af", "st", "tn", "xh", "zu"}},
	{cc: "ZM", name: "Zambia", languages: []string{"en"}},
	{cc: "ZW", name: "Zimbabwe", languages: []string{"en", "sn", "nd"}},
}
